#!/bin/sh
# -*- sh -*-

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "config" ]; then

        echo 'graph_title ElasticSearch open files'
        echo 'graph_args --base 1000 -l 0'
        echo 'graph_vlabel number of open files'
        echo 'graph_category system'
        echo 'used.label open files'
        echo 'used.type GAUGE'
        echo 'used.info The number of currently open files.'
        echo 'max.label max open files'
        echo 'max.type GAUGE'
        exit 0
fi

PID=`ps -u elasticsearch -opid,comm | grep java | awk '{ print $1 }'`
VALUE=`ls /proc/$PID/fd/ | wc | awk '{ print $1 }'`
MAX_VALUE=`grep 'Max open files' /proc/$PID/limits | awk '{ print $5 }'`
echo "used.value $VALUE"
echo "max.value $MAX_VALUE"
